### ISSUE TITLE
可以考虑使用我画的麻将图

### ISSUE THREAD

**Issue by lietxia** [nikmomo/riichi_mahjong_point_display_livestream#1]
可以随意商用
https://github.com/lietxia/mahjong_graphic
![preview](https://github.com/lietxia/mahjong_graphic/raw/main/preview.png)

**Comment by nikmomo** [comment]
Lietxia,
十分感谢你的分享！

Shin Z

lietxia ***@***.***>于2023年9月11日 周一05:17写道：
