### ISSUE TITLE
建议增加一个切上满贯的开关...

### ISSUE THREAD

**Issue by zhengye1** [nikmomo/riichi_mahjong_point_display_livestream#2]
30符4翻跟60符3翻是有切上跟不切上的说法..然而现在的系统只支持切上满贯

**Comment by nikmomo** [comment]
好的，这几天做个小更新

Vincent Zheng ***@***.***>于2023年12月6日 周三02:32写道：

**Comment by nikmomo** [comment]
你好，看了一下目前的系统是没有开启切上满贯的，如果想切上的话直接手动选择满贯就行
![image](https://github.com/nikmomo/riichi_mahjong_point_display_livestream/assets/89442374/6e755d0e-e5d5-4073-8870-ebb4d6f107fd)
![image](https://github.com/nikmomo/riichi_mahjong_point_display_livestream/assets/89442374/707c7779-b8e9-46ca-a7c1-36ce620ee487)
