### ISSUE TITLE
vs运行崩溃

### ISSUE THREAD

**Issue by curtain089AK** [nikmomo/riichi_mahjong_point_display_livestream#3]
<img width="1280" alt="微信图片_20240529104804" src="https://github.com/nikmomo/Riichi-Display/assets/171108554/a1a54dc5-bec9-4d83-b57e-f3725984c22b">
疑似这个players没有值？

**Comment by nikmomo** [comment]
你好，这是初次运行时的报错吗？

**Comment by curtain089AK** [comment]
感谢回复。是的，初次运行会崩溃。然后进调试模式有这个提示

**Comment by nikmomo** [comment]
可以尝试使用管理员身份运行vs，如果还是不行的话可能是有bug了

Shin Zhang
________________________________
发件人: curtain089AK ***@***.***>
发送时间: Wednesday, May 29, 2024 12:14:48 PM
收件人: nikmomo/Riichi-Display ***@***.***>
抄送: Zhang, Shin ***@***.***>; Comment ***@***.***>
主题: Re: [nikmomo/Riichi-Display] vs运行崩溃 (Issue #3)


感谢回复。是的，初次运行会崩溃。然后进调试模式有这个提示

―

**Comment by curtain089AK** [comment]
感谢回复。管理员身份运行vs情况相同，我可以使用这个带可执行文件的版本 [V2.0.1 Fixed Release]
以后有空我也可以尝试修复bug

**Comment by curtain089AK** [comment]
感谢回复。管理员身份运行vs情况相同，我可以使用这个带可执行文件的版本 [V2.0.1 Fixed Release]
以后有空我也可以尝试修复bug

**Comment by nikmomo** [comment]
好的，感谢。有可能是初始化player list失败了

Shin Zhang
________________________________
发件人: curtain089AK ***@***.***>
发送时间: Wednesday, May 29, 2024 12:51:02 PM
收件人: nikmomo/Riichi-Display ***@***.***>
抄送: Zhang, Shin ***@***.***>; Comment ***@***.***>
主题: Re: [nikmomo/Riichi-Display] vs运行崩溃 (Issue #3)


感谢回复。管理员身份运行vs情况相同，我可以使用这个带可执行文件的版本 [V2.0.1 Fixed Release]
以后有空我也可以尝试修复bug

―
