### ISSUE TITLE
建议在README.md中增加如build跟运行...

### ISSUE THREAD

**Issue by zhengye1** [nikmomo/riichi_mahjong_point_display_livestream#4]
重新捣鼓了一下然后发现我build也不行debug也不行..完全没头绪了...因为release里放的是source code...要不就告诉人家怎么build跟运行，要不就打包成一个exe文件一键开启？

**Comment by nikmomo** [comment]
好的，回头会更新
你可以在Visual Studio里安装WinForm相关的开发包，之后就应该可以使用了

**Comment by nikmomo** [comment]
已经更新readme和release
